/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Image;
import java.awt.Shape;
import javax.swing.ImageIcon;

/**
 *
 * @author Miguel Falcon
 */
public class AnimationCargando extends javax.swing.JFrame {
public ImageIcon imagenes[] = new ImageIcon[45];
    /**
     * Creates new form vistaAnimacion
     */
    public AnimationCargando() {
          
 
 

        
        initComponents();
        setLocationRelativeTo(null);
        imagenes[0]= new ImageIcon("fondo (1).jpg");
        imagenes[1]= new ImageIcon("fondo (2).jpg");
        imagenes[2]= new ImageIcon("fondo (3).jpg");
        imagenes[3]= new ImageIcon("fondo (4).jpg");
        imagenes[4]= new ImageIcon("fondo (5).jpg");
        imagenes[5]= new ImageIcon("fondo (6).jpg");
        imagenes[6]= new ImageIcon("fondo (7).jpg");
        imagenes[7]= new ImageIcon("fondo (8).jpg");
        imagenes[8]= new ImageIcon("fondo (9).jpg");
        imagenes[9]= new ImageIcon("fondo (10).jpg");
        imagenes[10]= new ImageIcon("fondo (11).jpg");
        imagenes[11]= new ImageIcon("fondo (12).jpg");
        imagenes[12]= new ImageIcon("fondo (13).jpg");
        imagenes[13]= new ImageIcon("fondo (14).jpg");
        imagenes[14]= new ImageIcon("fondo (15).jpg");
        imagenes[15]= new ImageIcon("fondo (16).jpg");
        imagenes[16]= new ImageIcon("fondo (17).jpg");
        imagenes[17]= new ImageIcon("fondo (18).jpg");
        imagenes[18]= new ImageIcon("fondo (19).jpg");
        imagenes[19]= new ImageIcon("fondo (20).jpg");
        imagenes[20]= new ImageIcon("fondo (21).jpg");
        imagenes[21]= new ImageIcon("fondo (22).jpg");
        imagenes[22]= new ImageIcon("fondo (23).jpg");
        imagenes[23]= new ImageIcon("fondo (24).jpg");
        imagenes[24]= new ImageIcon("fondo (25).jpg");
        imagenes[25]= new ImageIcon("fondo (26).jpg");
        imagenes[26]= new ImageIcon("fondo (27).jpg");
        imagenes[27]= new ImageIcon("fondo (28).jpg");
        imagenes[28]= new ImageIcon("fondo (29).jpg");
        imagenes[29]= new ImageIcon("fondo (30).jpg");
        imagenes[30]= new ImageIcon("fondo (31).jpg");
        imagenes[31]= new ImageIcon("fondo (32).jpg");
        imagenes[32]= new ImageIcon("fondo (33).jpg");
        imagenes[33]= new ImageIcon("fondo (34).jpg");
        imagenes[34]= new ImageIcon("fondo (35).jpg");
        imagenes[35]= new ImageIcon("fondo (36).jpg");
        imagenes[36]= new ImageIcon("fondo (37).jpg");
        imagenes[37]= new ImageIcon("fondo (38).jpg");
        imagenes[38]= new ImageIcon("fondo (39).jpg");
        imagenes[39]= new ImageIcon("fondo (40).jpg");
        imagenes[40]= new ImageIcon("fondo (41).jpg");
        imagenes[41]= new ImageIcon("fondo (42).jpg");
        imagenes[42]= new ImageIcon("fondo (43).jpg");
        imagenes[43]= new ImageIcon("fondo (44).jpg");
        imagenes[44]= new ImageIcon("fondo (45).jpg");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        cargando = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(null);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/log (2).png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(-170, 50, 690, 380);

        cargando.setFont(new java.awt.Font("Garamond", 0, 36)); // NOI18N
        cargando.setForeground(new java.awt.Color(8, 69, 129));
        cargando.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        cargando.setText("Cargando...");
        jPanel1.add(cargando);
        cargando.setBounds(220, 400, 370, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/loader05.gif"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 20, 540, 440);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnimationCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnimationCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnimationCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnimationCargando.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnimationCargando().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel cargando;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
