/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;



import java.awt.Dimension;
import javax.swing.JComponent;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;*/

public class FromEmpleado extends javax.swing.JInternalFrame {
 
    /**
     * Creates new form fromEmpleado
     */
    public FromEmpleado( ) {
        initComponents();
       // tablaEmpleado.setModel(empleado.cargarEmpleado());
          this.setBorder(null);
          this.QuitarLaBarraTitulo();
    }
      public void QuitarLaBarraTitulo()
{
        JComponent Barra = ((javax.swing.plaf.basic.BasicInternalFrameUI) getUI()).getNorthPane();
        Dimension DimensionBarra = Barra.getPreferredSize();
Barra.setSize(3,3);
Barra.setPreferredSize(new Dimension(0,0));
repaint();
}
public void limpiarID(){
    if(jtfEmpleadoID.getText().equals("")){
   // Vista.FromCliente.jtfClienteID.setText("");
    
  /*  Vista.FromProducto.jtfProductoID.setText("");
    Vista.FromProveedor.jtfProveedorID.setText("");
    Vista.FromFacturacion.jtfVentaID.setText("");
     tablaEmpleado.setModel(empleado.cargarEmpleado());*/
            jtfNombreID.setText("");
            jtfPuestoID.setText("");
            jtfPrivilegiosID.setText("");
            jtfUsuarioID.setText("");
            jtfContrasenaID.setText("");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbnNuevoEmpleado = new javax.swing.JButton();
        jtfEmpleadoID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfNombreID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfPuestoID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtfPrivilegiosID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtfUsuarioID = new javax.swing.JTextField();
        contrasena = new javax.swing.JLabel();
        jtfContrasenaID = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        jbnGuardar = new javax.swing.JButton();
        jbnEditar = new javax.swing.JButton();
        jbnImprimir = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(218, 218, 218));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbnNuevoEmpleado.setBackground(new java.awt.Color(135, 206, 235));
        jbnNuevoEmpleado.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jbnNuevoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jbnNuevoEmpleado.setText("Registrar nuevo empleado");
        jbnNuevoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnNuevoEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(jbnNuevoEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 194, 30));

        jtfEmpleadoID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtfEmpleadoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmpleadoIDActionPerformed(evt);
            }
        });
        jtfEmpleadoID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfEmpleadoIDFocusLost(evt);
            }
        });
        jtfEmpleadoID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfEmpleadoIDKeyReleased(evt);
            }
        });
        jPanel2.add(jtfEmpleadoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 63, 20));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setText("Nombre:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 60, 20));

        jtfNombreID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtfNombreID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfNombreID.setEnabled(false);
        jtfNombreID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNombreIDActionPerformed(evt);
            }
        });
        jtfNombreID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfNombreIDKeyReleased(evt);
            }
        });
        jPanel2.add(jtfNombreID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 200, 20));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel8.setText("Puesto:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 50, 20));

        jtfPuestoID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtfPuestoID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfPuestoID.setEnabled(false);
        jPanel2.add(jtfPuestoID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 200, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel9.setText("Código:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel10.setText("Privilegios:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 60, -1));

        jtfPrivilegiosID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtfPrivilegiosID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfPrivilegiosID.setEnabled(false);
        jPanel2.add(jtfPrivilegiosID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 220, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel11.setText("Usuario:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 50, 20));

        jtfUsuarioID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtfUsuarioID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfUsuarioID.setEnabled(false);
        jPanel2.add(jtfUsuarioID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 220, 20));

        contrasena.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        contrasena.setText("Contraseña:");
        jPanel2.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 70, 10));

        jtfContrasenaID.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jtfContrasenaID.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jtfContrasenaID.setEnabled(false);
        jPanel2.add(jtfContrasenaID, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 220, 20));

        tablaEmpleado.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tablaEmpleado);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 630, 200));

        jbnGuardar.setBackground(new java.awt.Color(154, 205, 50));
        jbnGuardar.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jbnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        jbnGuardar.setText("Guardar");
        jbnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jbnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 360, 100, 30));

        jbnEditar.setBackground(new java.awt.Color(112, 128, 144));
        jbnEditar.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jbnEditar.setForeground(new java.awt.Color(255, 255, 255));
        jbnEditar.setText("Editar");
        jbnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnEditarActionPerformed(evt);
            }
        });
        jPanel2.add(jbnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 100, 30));

        jbnImprimir.setBackground(new java.awt.Color(255, 204, 204));
        jbnImprimir.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jbnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        jbnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/printchi.png"))); // NOI18N
        jbnImprimir.setText("Imprimir reporte ");
        jbnImprimir.setBorder(null);
        jbnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnImprimirActionPerformed(evt);
            }
        });
        jPanel2.add(jbnImprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 180, 30));

        fondo.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoConsulta.jpg"))); // NOI18N
        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 430));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnNuevoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnNuevoEmpleadoActionPerformed

    }//GEN-LAST:event_jbnNuevoEmpleadoActionPerformed

    private void jtfNombreIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNombreIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNombreIDActionPerformed

    private void jtfNombreIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombreIDKeyReleased
     
    }//GEN-LAST:event_jtfNombreIDKeyReleased

    private void jbnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnGuardarActionPerformed
      
    }//GEN-LAST:event_jbnGuardarActionPerformed

    private void jbnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnEditarActionPerformed

    }//GEN-LAST:event_jbnEditarActionPerformed

    private void jtfEmpleadoIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfEmpleadoIDKeyReleased
      
    }//GEN-LAST:event_jtfEmpleadoIDKeyReleased

    private void jtfEmpleadoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmpleadoIDActionPerformed
       
    }//GEN-LAST:event_jtfEmpleadoIDActionPerformed

    private void jbnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnImprimirActionPerformed
      /*  String Reporte= "C:\\Users\\1073627831\\Documents\\NetBeansProjects\\SanGabriel_Farmacia\\src\\Reportes\\DbEmpleado.jasper";
        JasperReport jr=null;
        try {
            Connection conexion= DriverManager.getConnection("jdbc:mysql://localhost:3306/farmaciasangabriel", "root", "");
            jr=(JasperReport) JRLoader.loadObject(Reporte);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,conexion);
            JasperViewer jv=new JasperViewer(jp,false);
            jv.setTitle(Reporte);
            jv.setVisible(true);
            conexion.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }*/
    }//GEN-LAST:event_jbnImprimirActionPerformed

    private void jtfEmpleadoIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfEmpleadoIDFocusLost
this.limpiarID();        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmpleadoIDFocusLost

   
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contrasena;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbnEditar;
    private javax.swing.JButton jbnGuardar;
    private javax.swing.JButton jbnImprimir;
    private javax.swing.JButton jbnNuevoEmpleado;
    private javax.swing.JTextField jtfContrasenaID;
    public static javax.swing.JTextField jtfEmpleadoID;
    private javax.swing.JTextField jtfNombreID;
    private javax.swing.JTextField jtfPrivilegiosID;
    private javax.swing.JTextField jtfPuestoID;
    private javax.swing.JTextField jtfUsuarioID;
    public static javax.swing.JTable tablaEmpleado;
    // End of variables declaration//GEN-END:variables
}
